# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='balance')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Product')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repository',
            },
        ),
    ]
