# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20170724_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomposition',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.Dish'),
        ),
    ]
